"""add Department

Revision ID: 49811cef44d4
Revises: f7153ba9c4cd
Create Date: 2024-09-02 13:05:29.404820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49811cef44d4'
down_revision = 'f7153ba9c4cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
